title: SAUVC
longname: Singapore AUV Challenge
description: Explore the wonders underwater robotics world at Singapore AUV Challenge
website: "https://sauvc.org"
url: "https://sauvc.org"
image_path: img/sauvc-2017.jpg
markdown: kramdown
permalink: /:title
google_analytics: UA-105062391-1
twitter: sauvc
github:
  repository_url: https://github.com/sauvc/sauvc.github.io
exclude: ["Gemfile", "Gemfile.lock", "contributing.md", "Makefile"]
